<?php

namespace OvertimeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\Date;

/**
 * OvertimeHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OvertimeHoursRepository extends EntityRepository
{


}
