<?php

namespace OvertimeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\Date;

/**
 * OvertimeHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OvertimeHoursRepository extends EntityRepository
{
    public  function findOvertimesBetweenDates($user_id, $startDate, $endDate)
    {
        $sql = "SELECT p 
                FROM OvertimeBundle:OvertimeHours p 
                WHERE p.user_id = :user_id 
                and p.startDate BETWEEN :startDate and :endDate
                and p.endDate BETWEEN :startDate and :endDate";
    }
}
